sudo: false
language: node_js
node_js:
  - '5'
env:
  - CXX=g++-4.8

cache:
  directories:
    - node_modules

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint

after_success:
  - tools/docker-build.sh
