sudo: false
language: node_js
cache:
  directories:
  - node_modules
services:
- docker
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  - ALGOLIA_INDEX_PREFIX=travisci

branches:
  only:
    - master
    # Build any branch or tag whose name matches the format consisting of any
    # number of digits separated by periods, since that matches our release tag
    # format.
    - /^(\d+)(\.\d+)*$/

before_install:
- cp config.example.yml config.yml
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run lint
- npm run test
- "./travis-testcafe.sh"
after_success:
- tools/docker-build.sh
