# This file has magic strings that we later substitute out at Docker runtime

GOOGLE_API_KEY: "AIzaSyAz2oiKYp048xbbjXH54PrNDdQO38I6-pc"

ALGOLIA_INDEX_PREFIX: "davidagustin"
ALGOLIA_APPLICATION_ID: "J8TVT53HPZ"
ALGOLIA_READ_ONLY_API_KEY: "fdf77b152ff7ce0ea4e4221ff3d17d85"

MOHCD_SUBDOMAIN: "testing"
# uncomment this to simulate sfserviceguide whitelabel UI locally, assuming that
# you're pointing to localhost:8080
# MOHCD_DOMAIN: 'localhost:8080'

SFFAMILIES_DOMAIN: "SFFAMILIES_DOMAIN_REPLACE_ME"

LINKSF_DOMAIN: "LINKSF_DOMAIN_REPLACE_ME"

AUTH0_AUDIENCE: "http://localhost:8080/api"
AUTH0_CLIENT_ID: "UcnuRrX6S0SeDEhW9PRe01wEhcvIRuwc"
AUTH0_DOMAIN: "dev-nykixf8szsm220fi.us.auth0.com"
AUTH0_REDIRECT_URI: "http://localhost:8080/auth"
