// Admin actions
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_ERROR = 'ADMIN_LOGIN_ERROR';
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';


// User actions
export const SET_USER_LOCATION = 'SET_USER_LOCATION';


// Service actions
export const SERVICE_LOAD_REQUEST = 'SERVICE_LOAD_REQUEST';
export const SERVICE_LOAD_SUCCESS = 'SERVICE_LOAD_SUCCESS';
export const SERVICE_LOAD_ERROR = 'SERVICE_LOAD_ERROR';

export const SERVICES_LOAD_REQUEST = 'SERVICES_LOAD_REQUEST';
export const SERVICES_LOAD_SUCCESS = 'SERVICES_LOAD_SUCCESS';
export const SERVICES_LOAD_ERROR = 'SERVICES_LOAD_ERROR';


export const adminActions = {
  ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
  ADMIN_LOGIN_ERROR: 'ADMIN_LOGIN_ERROR',
  ADMIN_LOGIN_REQUEST: 'ADMIN_LOGIN_REQUEST',
};

export const userActions = {
  SET_USER_LOCATION: 'SET_USER_LOCATION',
};

export const serviceActions = {
  SERVICE_LOAD_REQUEST: 'SERVICE_LOAD_REQUEST',
  SERVICE_LOAD_SUCCESS: 'SERVICE_LOAD_SUCCESS',
  SERVICE_LOAD_ERROR: 'SERVICE_LOAD_ERROR',

  SERVICES_BY_CATEGORY_LOAD_REQUEST: 'SERVICES_BY_CATEGORY_LOAD_REQUEST',
  SERVICES_BY_CATEGORY_LOAD_SUCCESS: 'SERVICES_BY_CATEGORY_LOAD_SUCCESS',
  SERVICES_BY_CATEGORY_LOAD_ERROR: 'SERVICES_BY_CATEGORY_LOAD_ERROR',

  SERVICES_COUNT_REQUEST: 'SERVICES_COUNT_REQUEST',
  SERVICES_COUNT_SUCCESS: 'SERVICES_COUNT_SUCCESS',
  SERVICES_COUNT_ERROR: 'SERVICES_COUNT_ERROR',

  SERVICES_CHANGE_REQUEST_REQUEST: 'SERVICES_CHANGE_REQUEST_REQUEST',
  SERVICES_CHANGE_REQUEST_SUCCESS: 'SERVICES_CHANGE_REQUEST_SUCCESS',
  SERVICES_CHANGE_REQUEST_ERROR: 'SERVICES_CHANGE_REQUEST_ERROR',

  ADD_NOTE_TO_SERVICE_REQUEST: 'ADD_NOTE_TO_SERVICE_REQUEST',
  ADD_NOTE_TO_SERVICE_SUCCESS: 'ADD_NOTE_TO_SERVICE_SUCCESS',
  ADD_NOTE_TO_SERVICE_ERROR: 'ADD_NOTE_TO_SERVICE_ERROR',
};

export const categoryActions = {
  CATEGORIES_LOAD_REQUEST: 'CATEGORIES_LOAD_REQUEST',
  CATEGORIES_LOAD_SUCCESS: 'CATEGORIES_LOAD_SUCCESS',
  CATEGORIES_LOAD_ERROR: 'CATEGORIES_LOAD_ERROR',

  FEATURED_CATEGORIES_LOAD_REQUEST: 'FEATURED_CATEGORIES_LOAD_REQUEST',
  FEATURED_CATEGORIES_LOAD_SUCCESS: 'FEATURED_CATEGORIES_LOAD_SUCCESS',
  FEATURED_CATEGORIES_LOAD_ERROR: 'FEATURED_CATEGORIES_LOAD_ERROR',
};

export const eligibilityActions = {
  ELIGIBILITIES_LOAD_REQUEST: 'ELIGIBILITIES_LOAD_REQUEST',
  ELIGIBILITIES_LOAD_SUCCESS: 'ELIGIBILITIES_LOAD_SUCCESS',
  ELIGIBILITIES_LOAD_ERROR: 'ELIGIBILITIES_LOAD_ERROR',

  FEATURED_ELIGIBILITIES_LOAD_REQUEST: 'FEATURED_ELIGIBILITIES_LOAD_REQUEST',
  FEATURED_ELIGIBILITIES_LOAD_SUCCESS: 'FEATURED_ELIGIBILITIES_LOAD_SUCCESS',
  FEATURED_ELIGIBILITIES_LOAD_ERROR: 'FEATURED_ELIGIBILITIES_LOAD_ERROR',

  UPDATE_ELIGIBILITY_RANK_REQUEST: 'UPDATE_ELIGIBILITY_RANK_REQUEST',
  UPDATE_ELIGIBILITY_RANK_SUCCESS: 'UPDATE_ELIGIBILITY_RANK_SUCCESS',
  UPDATE_ELIGIBILITY_RANK_ERROR: 'UPDATE_ELIGIBILITY_RANK_ERROR',
};

export const resourceActions = {
  RESOURCE_LOAD_REQUEST: 'RESOURCE_LOAD_REQUEST',
  RESOURCE_LOAD_SUCCESS: 'RESOURCE_LOAD_SUCCESS',
  RESOURCE_LOAD_ERROR: 'RESOURCE_LOAD_ERROR',

  RESOURCES_LOAD_REQUEST: 'RESOURCES_LOAD_REQUEST',
  RESOURCES_LOAD_SUCCESS: 'RESOURCES_LOAD_SUCCESS',
  RESOURCES_LOAD_ERROR: 'RESOURCES_LOAD_ERROR',

  FEATURED_RESOURCES_LOAD_REQUEST: 'FEATURED_RESOURCES_LOAD_REQUEST',
  FEATURED_RESOURCES_LOAD_SUCCESS: 'FEATURED_RESOURCES_LOAD_SUCCESS',
  FEATURED_RESOURCES_LOAD_ERROR: 'FEATURED_RESOURCES_LOAD_ERROR',

  RESOURCE_COUNT_REQUEST: 'RESOURCE_COUNT_REQUEST',
  RESOURCE_COUNT_SUCCESS: 'RESOURCE_COUNT_SUCCESS',
  RESOURCE_COUNT_ERROR: 'RESOURCE_COUNT_ERROR',

  RESOURCES_BY_CATEGORY_ID_REQUEST: 'RESOURCES_BY_CATEGORY_ID_REQUEST',
  RESOURCES_BY_CATEGORY_ID_SUCCESS: 'RESOURCES_BY_CATEGORY_ID_REQUEST',
  RESOURCES_BY_CATEGORY_ID_ERROR: 'RESOURCES_BY_CATEGORY_ID_REQUEST',

  SEARCH_FOR_RESOURCES_REQUEST: 'SEARCH_FOR_RESOURCES_REQUEST',
  SEARCH_FOR_RESOURCES_SUCCESS: 'SEARCH_FOR_RESOURCES_SUCCESS',
  SEARCH_FOR_RESOURCES_ERROR: 'SEARCH_FOR_RESOURCES_SUCCESS',

  RESOURCES_BY_ID_SORT_LOC_LOAD_REQUEST: 'RESOURCES_BY_ID_SORT_LOC_LOAD_REQUEST',
  RESOURCES_BY_ID_SORT_LOC_LOAD_SUCCESS: 'RESOURCES_BY_ID_SORT_LOC_LOAD_SUCCESS',
  RESOURCES_BY_ID_SORT_LOC_LOAD_ERROR: 'RESOURCES_BY_ID_SORT_LOC_LOAD_ERROR',

  SEARCH_RESOURCES_SORT_LOC_REQUEST: 'SEARCH_RESOURCES_SORT_LOC_REQUEST',
  SEARCH_RESOURCES_SORT_LOC_SUCCESS: 'SEARCH_RESOURCES_SORT_LOC_SUCCESS',
  SEARCH_RESOURCES_SORT_LOC_ERROR: 'SEARCH_RESOURCES_SORT_LOC_ERROR',

  SUBMIT_NEW_RESOURCE_REQUEST: 'SUBMIT_NEW_RESOURCE_REQUEST',
  SUBMIT_NEW_RESOURCE_SUCCESS: 'SUBMIT_NEW_RESOURCE_SUCCESS',
  SUBMIT_NEW_RESOURCE_ERROR: 'SUBMIT_NEW_RESOURCE_ERROR',

  SUBMIT_NEW_SERVICE_REQUEST: 'SUBMIT_NEW_SERVICE_REQUEST',
  SUBMIT_NEW_SERVICE_SUCCESS: 'SUBMIT_NEW_SERVICE_SUCCESS',
  SUBMIT_NEW_SERVICE_ERROR: 'SUBMIT_NEW_SERVICE_ERROR',

  SUBMIT_RESOURCE_CHANGE_REQUEST: 'SUBMIT_RESOURCE_CHANGE_REQUEST',
  SUBMIT_RESOURCE_CHANGE_SUCCESS: 'SUBMIT_RESOURCE_CHANGE_SUCCESS',
  SUBMIT_RESOURCE_CHANGE_ERROR: 'SUBMIT_RESOURCE_CHANGE_ERROR',

  ADD_NOTE_TO_RESOURCE_REQUEST: 'ADD_NOTE_TO_RESOURCE_REQUEST',
  ADD_NOTE_TO_RESOURCE_SUCCESS: 'ADD_NOTE_TO_RESOURCE_SUCCESS',
  ADD_NOTE_TO_RESOURCE_ERROR: 'ADD_NOTE_TO_RESOURCE_ERROR',

  VERIFY_RESOURCE_REQUEST: 'VERIFY_RESOURCE_REQUEST',
  VERIFY_RESOURCE_SUCCESS: 'VERIFY_RESOURCE_SUCCESS',
  VERIFY_RESOURCE_ERROR: 'VERIFY_RESOURCE_ERROR',

  CERTIFY_RESOURCE_HAP_REQUEST: 'CERTIFY_RESOURCE_HAP_REQUEST',
  CERTIFY_RESOURCE_HAP_SUCCESS: 'CERTIFY_RESOURCE_HAP_SUCCESS',
  CERTIFY_RESOURCE_HAP_ERROR: 'CERTIFY_RESOURCE_HAP_ERROR',

  DEACTIVATE_RESOURCE_REQUEST: 'DEACTIVATE_RESOURCE_REQUEST',
  DEACTIVATE_RESOURCE_SUCCESS: 'DEACTIVATE_RESOURCE_SUCCESS',
  DEACTIVATE_RESOURCE_ERROR: 'DEACTIVATE_RESOURCE_ERROR',
};
