export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_ERROR = 'ADMIN_LOGIN_ERROR';
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';

// Pop-Up Message actions
export const SHOW_POP_UP_MESSAGE = 'SHOW_POP_UP_MESSAGE';
export const HIDE_POP_UP_MESSAGE = 'HIDE_POP_UP_MESSAGE';
