import type { WebAuth, Auth0Result } from "auth0-js";
import { defaultAuthObject } from "components/AppProvider";
import { get } from "utils/DataService";
import type { AuthState } from "components/AppProvider";

/*
  This class provides a set of methods that serve as an interface between our application
  and the Auth0 servers where the user's state and data is stored.
*/

export default class AuthService {
  static calculateSessionExpiration(secondsUntilExpiration: number) {
    const currentTime = new Date();
    const expirationTime = new Date(
      currentTime.getTime() + secondsUntilExpiration * 1000
    );

    return expirationTime;
  }

  static persistUser(hash: string, authClient: WebAuth, setAuthState: any) {
    authClient.parseHash({ hash }, (err, authResult) => {
      if (err) {
        // TODO: Handle errors
      }

      if (authResult?.accessToken) {
        const { accessToken, expiresIn, idTokenPayload } = authResult;
        const authObject = {
          isAuthenticated: true,
          user: {
            email: idTokenPayload.email,
            id: idTokenPayload.sub,
          },
          accessTokenObject: {
            token: accessToken,
            expiresAt: expiresIn
              ? this.calculateSessionExpiration(expiresIn)
              : null,
          },
        };

        setAuthState(authObject);
      }
    });
  }

  static signUpUser = (authClient: WebAuth, email: string) => {
    return new Promise((resolve, reject) => {
      AuthService.userExists(email).then((exists) => {
        if (!exists) {
          // Todo: save the user's email/name/org to our database along with the ID generated by
          // auth0 on successful sign up
          resolve(AuthService.passwordlessStart(authClient, email));
        } else {
          reject(new Error('userExists'));
        }
      });
    });
  };

  // This method initiates the sign-in/sign-up process by sending a code
  // to the user's inbox.
  static passwordlessStart = (authClient: WebAuth, email: string) => {
    return new Promise((resolve, reject) => {
      authClient.passwordlessStart(
        {
          connection: "email",
          send: "code",
          email,
        },
        (err) => {
          if (err) {
            reject(err);
            return;
          }

          resolve(true);
        }
      );
    });
  };

  // This method passes the user's verification code to Auth0's server, which
  // completes their sign-up/log-in action
  static passwordlessVerify = (
    authClient: WebAuth,
    email: string,
    verificationCode: string
  ) => {
    authClient.passwordlessLogin(
      {
        connection: "email",
        email,
        verificationCode,
      },
      (err) => {
        if (err) {
          // TODO: Handle errors
        }
      }
    );
  };

  static logout = (
    authClient: WebAuth,
    clientId: string,
    setAuthState: (state: AuthState) => void
  ) => {
    setAuthState(defaultAuthObject);

    authClient.logout({
      returnTo: "http://localhost:8080",
      clientID: clientId,
    });
  };

  static hasAccessTokenExpired = (tokenExpiration: Date) => {
    return !tokenExpiration || (new Date(tokenExpiration) < new Date());
  };

  static refreshAccessToken = (authClient: WebAuth) => {
    return new Promise((resolve, reject) => {
      authClient.checkSession({}, (err, authResult: Auth0Result) => {
        if (err) {
          reject(err);
        } else {
          resolve(authResult);
        }
      });
    });
  };

  static userExists = (email: string) => {
    return new Promise((resolve, reject) => {
      const response = get(`/api/auth/user_exists?email=${email}`);
      response.then((result) => {
        resolve(result.user_exists);
      }, (error) => {
        reject(error);
      })
    });
  }
}
